In [1]:
# 1️⃣ Load the dataset

In [10]:
import pandas as pd

df = pd.read_csv("california_housing.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [11]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [13]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [14]:
df.shape

(20640, 10)

Step 3 — Separate X and y

Now that we know what we're trying to predict, we can actually perform the ML operation.

In [15]:
X = df.drop(columns = "median_house_value")
y = df["median_house_value"]

In [16]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [17]:
y # Target variable (y) = median_house_value

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

Step 4 — Verify

In [18]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (20640, 9)
y shape: (20640,)

🧪 Practical Lesson 2 — Train/Test Split

🎯 Objective

We want to train a model that learns the relationship between:

Housing features → Median house value

But there's a problem:

If we train and evaluate the model on the same data, we can't properly know whether it can generalize to new houses.

So we divide the data into:

                 FULL DATASET
                      ↓
              Train/Test Split
                 ↙        ↘
          Training data   Test data
             ↓               ↓
          LEARN           UNSEEN
             ↓               ↓
          Model        Final evaluation

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

In [20]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (16512, 9)
X_test shape: (4128, 9)
y_train shape: (16512,)
y_test shape: (4128,)

Check the training data

In [21]:
X_train.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
dtype: int64

In [22]:
X_test.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [23]:
# Create the imputer

In [24]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = "median")

imputer.fit(X_train[["total_bedrooms"]])
X_train["total_bedrooms"] = imputer.transform(X_train[["total_bedrooms"]])

In [25]:
# Transform X_test

In [26]:
X_test["total_bedrooms"] = imputer.transform(
    X_test[["total_bedrooms"]]
)

In [27]:
# verify

In [28]:
X_train.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
dtype: int64

In [29]:
X_test.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
dtype: int64

Categorical Encoding

Our California Housing dataset has a categorical feature:

ocean_proximity

It contains text categories such as:

<1H OCEAN
INLAND
NEAR OCEAN
NEAR BAY
ISLAND

A Linear Regression model cannot directly calculate with strings like "INLAND".

So we need to encode the categories into numbers.

🎯 Step 1 — See our actual categories

In [30]:
X_train["ocean_proximity"].value_counts()

ocean_proximity
<1H OCEAN     7341
INLAND        5227
NEAR OCEAN    2086
NEAR BAY      1854
ISLAND           4
Name: count, dtype: int64

In [31]:
# One-Hot Encoding

In [32]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown="ignore")
encoder.fit(X_train[["ocean_proximity"]])

X_train_encoded = encoder.transform(X_train[["ocean_proximity"]])

In [33]:
X_test_encoded = encoder.transform(
    X_test[["ocean_proximity"]]
)

In [34]:
# To see what we created

In [35]:
encoder.get_feature_names_out(["ocean_proximity"])

array(['ocean_proximity_<1H OCEAN', 'ocean_proximity_INLAND',
       'ocean_proximity_ISLAND', 'ocean_proximity_NEAR BAY',
       'ocean_proximity_NEAR OCEAN'], dtype=object)

In [36]:
# Identify numerical columns

In [37]:
X_train.select_dtypes(include="number").columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='str')

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numeric_cols = X_train.select_dtypes(include="number").columns
scaler.fit(X_train[numeric_cols])
X_train_scaled = scaler.transform(
    X_train[numeric_cols]
)

In [39]:
X_test_scaled = scaler.transform(
    X_test[numeric_cols]
)

In [40]:
# Check the result

In [41]:
X_train_scaled.mean(axis=0)

array([ 1.77678716e-15,  3.38574991e-15, -1.67824411e-17,  3.52861581e-17,
       -4.47531762e-17,  0.00000000e+00, -5.50808322e-17, -6.41175313e-17])

In [42]:
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
# outlier detection
# Choose a numerical feature

In [44]:
X_train["total_rooms"].describe()

count    16512.000000
mean      2642.004784
std       2174.646744
min          2.000000
25%       1454.000000
50%       2129.000000
75%       3160.000000
max      39320.000000
Name: total_rooms, dtype: float64

In [45]:
Q1 = X_train["total_rooms"].quantile(0.25)
Q3 = X_train["total_rooms"].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 1454.0
Q3: 3160.0
IQR: 1706.0

In [46]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower boundary:", lower)
print("Upper boundary:", upper)

Lower boundary: -1105.0
Upper boundary: 5719.0

In [47]:
outliers = X_train[X_train["total_rooms"] > upper
    ]
print("Number of potential outlier:", len(outliers))

Number of potential outlier: 1046

In [48]:
outliers["total_rooms"].describe()

count     1046.000000
mean      8755.678776
std       3890.511003
min       5721.000000
25%       6339.000000
50%       7362.000000
75%       9613.750000
max      39320.000000
Name: total_rooms, dtype: float64

In [49]:
numeric_cols = X_train.select_dtypes(include="number").columns

outlier_summary = []

for col in numeric_cols:
    Q1 = X_train[col].quantile(0.25)
    Q3 = X_train[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((X_train[col] < lower) | (X_train[col] > upper)).sum()

    outlier_summary.append([col, count, lower, upper])

outlier_summary = pd.DataFrame(
    outlier_summary,
    columns=["Feature", "Outlier_Count", "Lower_Bound", "Upper_Bound"]
)

outlier_summary

              Feature  Outlier_Count  Lower_Bound  Upper_Bound
0           longitude              0  -127.510000  -112.310000
1            latitude              0    28.245000    43.405000
2  housing_median_age              0   -10.500000    65.500000
3         total_rooms           1046 -1105.000000  5719.000000
4      total_bedrooms           1041  -228.625000  1172.375000
5          population            955  -616.500000  3131.500000
6          households            977  -209.000000  1095.000000
7       median_income            529    -0.743013     8.082888

In [50]:
X_train["total_bedrooms"].describe()

count    16512.000000
mean       538.496851
std        419.007096
min          1.000000
25%        296.750000
50%        437.000000
75%        647.000000
max       6445.000000
Name: total_bedrooms, dtype: float64

In [51]:
X_train["median_income"].describe()

count    16512.000000
mean         3.880754
std          1.904294
min          0.499900
25%          2.566700
50%          3.545800
75%          4.773175
max         15.000100
Name: median_income, dtype: float64

In [52]:
#Feature Engineering

In [53]:
# Create rooms_per_household

In [54]:
X_train["rooms_per_household"] = (
    X_train["total_rooms"] / X_train["households"]
)
X_test["rooms_per_household"] = (
    X_test["total_rooms"] / X_test["households"]
)

In [55]:
# bedrooms_per_room
X_train["bedrooms_per_room"] = (
    X_train["total_bedrooms"] / X_train["total_rooms"]
)

X_test["bedrooms_per_room"] = (
    X_test["total_bedrooms"] / X_test["total_rooms"]
)

In [56]:
X_train["population_per_household"] = (
    X_train["population"] / X_train["households"]
)

X_test["population_per_household"] = (
    X_test["population"] / X_test["households"]
)

In [57]:
X_train[
    [
        "rooms_per_household",
        "bedrooms_per_room",
        "population_per_household"
    ]
].head()

       rooms_per_household  bedrooms_per_room  population_per_household
14196             5.017657           0.200576                  3.691814
8267              4.473545           0.232703                  1.738095
17445             5.645833           0.174486                  2.723214
14265             4.002817           0.258269                  3.994366
2271              6.268421           0.180940                  2.300000

In [58]:
# Look at correlations with our target

In [59]:
y_train

14196    103000.0
8267     382100.0
17445    172600.0
14265     93400.0
2271      96500.0
           ...
11284    229200.0
11964     97800.0
5390     222100.0
860      283500.0
15795    325000.0
Name: median_house_value, Length: 16512, dtype: float64

In [60]:
train_analysis = X_train.copy()
train_analysis["median_house_value"] = y_train

In [61]:
#Calculate correlations

In [62]:
correlations = train_analysis.corr(numeric_only=True)["median_house_value"]
correlations.sort_values(ascending=False)

median_house_value          1.000000
median_income               0.690647
rooms_per_household         0.158485
total_rooms                 0.133989
housing_median_age          0.103706
households                  0.063714
total_bedrooms              0.047980
population_per_household   -0.022030
population                 -0.026032
longitude                  -0.046349
latitude                   -0.142983
bedrooms_per_room          -0.257419
Name: median_house_value, dtype: float64

In [63]:
feature_corr = X_train.corr(numeric_only=True)
feature_corr

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,rooms_per_household,bedrooms_per_room,population_per_household
longitude,1.000000,-0.924485,-0.101818,0.038676,0.063064,0.094276,0.049306,-0.017040,-0.029339,0.097280,-0.000598
latitude,-0.924485,1.000000,0.005296,-0.029224,-0.059998,-0.102499,-0.064061,-0.076571,0.110695,-0.118938,0.005837
housing_median_age,-0.101818,0.005296,1.000000,-0.360922,-0.320624,-0.292283,-0.302796,-0.121711,-0.160892,0.135495,0.016245
total_rooms,0.038676,-0.029224,-0.360922,1.000000,0.930489,0.857936,0.920482,0.198268,0.136090,-0.189316,-0.024991
total_bedrooms,0.063064,-0.059998,-0.320624,0.930489,1.000000,0.878932,0.980255,-0.009141,-0.001659,0.084149,-0.028536
population,0.094276,-0.102499,-0.292283,0.857936,0.878932,1.000000,0.907452,0.004122,-0.073733,0.035134,0.072330
households,0.049306,-0.064061,-0.302796,0.920482,0.980255,0.907452,1.000000,0.012776,-0.083062,0.064185,-0.027656
median_income,-0.017040,-0.076571,-0.121711,0.198268,-0.009141,0.004122,0.012776,1.000000,0.336013,-0.616669,0.022061
rooms_per_household,-0.029339,0.110695,-0.160892,0.136090,-0.001659,-0.073733,-0.083062,0.336013,1.000000,-0.435169,-0.004922
bedrooms_per_room,0.097280,-0.118938,0.135495,-0.189316,0.084149,0.035134,0.064185,-0.616669,-0.435169,1.000000,0.003938
population_per_household,-0.000598,0.005837,0.016245,-0.024991,-0.028536,0.072330,-0.027656,0.022061,-0.004922,0.003938,1.000000

# Build the Preprocessing Pipeline
"Whenever new data arrives, perform these preprocessing steps in this exact order."

This prevents mistakes and makes the workflow reproducible.

In [64]:
# Step 1 — Separate numerical and categorical columns

In [65]:
categorical_cols = ["ocean_proximity"]

In [66]:
# And we can automatically identify the numerical columns:

In [67]:
numeric_cols = X_train.select_dtypes(include="number").columns.tolist()

In [68]:
# Step 2 — Import the tools

In [69]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [70]:
# Step 3 — Build the numerical preprocessing pipeline

In [71]:
numeric_pipeline = Pipeline([("imputer", SimpleImputer(strategy="median")),("scaler", StandardScaler())])

In [72]:
# Step 4 — Build the categorical preprocessing pipeline

In [73]:
categorical_pipeline = Pipeline([("imputer", SimpleImputer(strategy="most_frequent")),
                                 ("encoder", OneHotEncoder(handle_unknown="ignore"))]
                               )

In [74]:
# Step 5 — Combine them with ColumnTransformer

In [75]:
preprocessor = ColumnTransformer([("numerical", numeric_pipeline, numeric_cols),
                                  ("categorical", categorical_pipeline, categorical_cols)
                                 ])

In [76]:
# Step 6 — Fit the preprocessor

In [77]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income',
                                  'rooms_per_household', 'bedrooms_per_room',
                                  'population_per_household']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['ocean_proximity'])])

In [78]:
X_train_processed = preprocessor.transform(X_train)

In [79]:
X_test_processed = preprocessor.transform(X_test)

In [80]:
# Step 7 Check the result

In [81]:
X_train_processed.shape
X_test_processed.shape

(4128, 16)

In [82]:
print("Training data:", X_train_processed.shape)
print("Test data:", X_test_processed.shape)

Training data: (16512, 16)
Test data: (4128, 16)

In [83]:
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

y_train: (16512,)
y_test: (4128,)

# 🌲 Model #3 — Random Forest Regression

🧠 Step 1 — Understand Random Forest

A Random Forest is essentially:

Many Decision Trees working together.

Instead of trusting one tree:

Data
 ↓
🌳 One Decision Tree
 ↓
Prediction

we build many trees:

                 Data
                  ↓
        ┌─────────┼─────────┐
        ↓         ↓         ↓
       🌳        🌳        🌳   ... many trees
        ↓         ↓         ↓
      $280k     $310k     $295k
        └─────────┼─────────┘
                  ↓
             Average
                  ↓
             💰 $295k

In [84]:
# 🚀 Step 2 — Import

In [85]:
from sklearn.ensemble import RandomForestRegressor

In [86]:
# Step 3 — Create Model #3

In [87]:
model_3 = RandomForestRegressor(
    random_state=42
)

In [88]:
# Step 4 — Train

In [89]:
model_3.fit(X_train_processed, y_train)

RandomForestRegressor(random_state=42)

In [90]:
# Step 5 — Predict

In [91]:
y_pred_3 = model_3.predict(X_test_processed)

# 📊 Next — Evaluate Model #3

In [93]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_3 = mean_absolute_error(y_test, y_pred_3)
mse_3 = mean_squared_error(y_test, y_pred_3)
rmse_3 = np.sqrt(mse_3)
r2_3 = r2_score(y_test, y_pred_3)

print("Model #3 — Random Forest Regression")
print("MAE :", mae_3)
print("MSE :", mse_3)
print("RMSE:", rmse_3)
print("R²  :", r2_3)

Model #3 — Random Forest Regression
MAE : 32325.262456395347
MSE : 2532578201.922123
RMSE: 50324.72753947231
R²  : 0.8067337568671218

# 🥇 Winner: Random Forest Regression

It wins on all three primary metrics:

Lowest MAE → predictions are closest on average.
Lowest RMSE → substantially fewer/severer large errors.
Highest R² → explains the largest proportion of variation.

So our decision is:

Random Forest Regression is the best candidate among the three models we tested. ✅

# 🏆 Step 7 — Finalize Our Winning Model
This is the important professional transition:

The user gives raw data. The system automatically prepares it and sends it to the model.

They don't need to manually perform imputation, encoding, or scaling.

In [94]:
# Create the final pipeline

In [95]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

final_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        random_state = 42
    ))
])

In [96]:
# Train the final pipeline

In [97]:
final_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['longitude', 'latitude',
                                                   'housing_median_age',
                                                   'total_rooms',
                                                   'total_bedrooms',
                                                   'population', 'households',
                                                   'median_income',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['ocean_proximity'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [99]:
# 💾 Step 8 — Save the Entire Prediction Machine
# We'll use joblib, which is commonly used to save scikit-learn models.

In [100]:
import joblib
joblib.dump(final_model, "california_housing_model.pkl")

['california_housing_model.pkl']

In [101]:
# Confirm the file exists

In [102]:
import os

print(os.path.exists("california_housing_model.pkl"))

True

In [103]:
# we can load the saved machine without rebuilding everything:
loaded_model = joblib.load("california_housing_model.pkl")

# 🏠 Step  Give Our Model a NEW House

In [105]:
# Create a new house

In [106]:
new_house = X_train.iloc[[0]].copy()

In [107]:
new_house["longitude"] = -118.25
new_house["latitude"] = 34.05
new_house["housing_median_age"] = 25
new_house["total_rooms"] = 2500
new_house["total_bedrooms"] = 500
new_house["population"] = 1200
new_house["households"] = 450
new_house["median_income"] = 6.5
new_house["ocean_proximity"] = "NEAR OCEAN"

# 🤖 Step Ask the prediction machine

In [108]:
prediction = final_model.predict(new_house)
print("Predicted median house value:", prediction[0])

Predicted median house value: 263729.0

# 💰 Step Get a Clean, Human-Readable Prediction

In [109]:
predicted_price = prediction[0]

print(f"Predicted median house value: ${predicted_price:,.0f}")

Predicted median house value: $263,729

# 🖥️ Step Build Our Prediction Interface

In [111]:
# Since you're working in a notebook, we'll use Gradio for a clean interactive interface.
# Install Gradio

In [117]:
%pip install gradio

Collecting gradio
  Using cached gradio-6.24.0-py3-none-any.whl.metadata (17 kB)
Collecting anyio<5.0,>=3.0 (from gradio)
  Downloading anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting audioop-lts<=0.2.2 (from gradio)
  Using cached audioop_lts-0.2.2-cp313-abi3-win_amd64.whl.metadata (2.0 kB)
Collecting brotli>=1.1.0 (from gradio)
  Using cached brotli-1.2.0-cp314-cp314-win_amd64.whl.metadata (6.3 kB)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Using cached fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Collecting gradio-client==2.6.0 (from gradio)
  Using cached gradio_client-2.6.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Using cached groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Collecting hf-gradio<1.0,>=0.4.1 (from gradio)
  Using cached hf_gradio-0.4.1-py3-none-any.whl.metadata (428 bytes)
Collecting httpx<1.0,>=0.24.1 (from gradio)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting huggingface-hub<2.0,>=1.16.0 (from gradio)
  Using cached huggingface_hub-1.27.0-py3-none-any.whl.metadata (16 kB)
Collecting jinja2<4.0 (from gradio)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe<4.0,>=2.0 (from gradio)
  Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from gradio) (2.5.0)
Collecting orjson~=3.0 (from gradio)
  Using cached orjson-3.12.0-cp314-cp314-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: packaging in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from gradio) (26.2)
Requirement already satisfied: pandas<4.0,>=1.0 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from gradio) (3.0.3)
Requirement already satisfied: pillow<13.0,>=8.0 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from gradio) (12.2.0)
Collecting pydantic<=3.0,>=2.0 (from gradio)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting pydub<1.0 (from gradio)
  Using cached pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart<1.0,>=0.0.18 (from gradio)
  Using cached python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting pytz>=2017.2 (from gradio)
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting pyyaml<7.0,>=5.0 (from gradio)
  Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Using cached safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<2.0,>=1.0.1 (from gradio)
  Using cached starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Collecting tomlkit<0.15.0,>=0.12.0 (from gradio)
  Using cached tomlkit-0.14.0-py3-none-any.whl.metadata (2.8 kB)
Collecting typer<1.0,>=0.12 (from gradio)
  Using cached typer-0.27.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions~=4.0 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from gradio) (4.15.0)
Collecting uvicorn>=0.14.0 (from gradio)
  Using cached uvicorn-0.52.3-py3-none-any.whl.metadata (6.6 kB)
Collecting fsspec (from gradio-client==2.6.0->gradio)
  Using cached fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna>=2.8 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.18)
Collecting typing-inspection>=0.4.2 (from fastapi<1.0,>=0.115.2->gradio)
  Using cached typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1.0,>=0.115.2->gradio)
  Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: certifi in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2026.6.17)
Collecting httpcore==1.* (from httpx<1.0,>=0.24.1->gradio)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.16.0->gradio)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub<2.0,>=1.16.0->gradio)
  Using cached filelock-3.32.3-py3-none-any.whl.metadata (2.0 kB)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0,>=1.16.0->gradio)
  Using cached hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting tqdm>=4.42.1 (from huggingface-hub<2.0,>=1.16.0->gradio)
  Using cached tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.16.0->gradio) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from pandas<4.0,>=1.0->gradio) (2026.2)
Collecting annotated-types>=0.6.0 (from pydantic<=3.0,>=2.0->gradio)
  Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<=3.0,>=2.0->gradio)
  Using cached pydantic_core-2.46.4-cp314-cp314-win_amd64.whl.metadata (6.7 kB)
Collecting shellingham>=1.3.0 (from typer<1.0,>=0.12->gradio)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer<1.0,>=0.12->gradio)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer<1.0,>=0.12->gradio)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached gradio-6.24.0-py3-none-any.whl (30.7 MB)
Using cached gradio_client-2.6.0-py3-none-any.whl (61 kB)
Downloading anyio-4.14.2-py3-none-any.whl (125 kB)
Using cached audioop_lts-0.2.2-cp313-abi3-win_amd64.whl (30 kB)
Using cached fastapi-0.141.1-py3-none-any.whl (131 kB)
Using cached groovy-0.1.2-py3-none-any.whl (14 kB)
Using cached hf_gradio-0.4.1-py3-none-any.whl (4.5 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached huggingface_hub-1.27.0-py3-none-any.whl (784 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Using cached orjson-3.12.0-cp314-cp314-win_amd64.whl (121 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp314-cp314-win_amd64.whl (2.1 MB)
Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Using cached python_multipart-0.0.32-py3-none-any.whl (30 kB)
Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Using cached safehttpx-0.1.7-py3-none-any.whl (9.0 kB)
Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Using cached starlette-1.6.0-py3-none-any.whl (75 kB)
Using cached tomlkit-0.14.0-py3-none-any.whl (39 kB)
Using cached typer-0.27.1-py3-none-any.whl (122 kB)
Using cached annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Using cached annotated_types-0.8.0-py3-none-any.whl (13 kB)
Using cached brotli-1.2.0-cp314-cp314-win_amd64.whl (375 kB)
Using cached filelock-3.32.3-py3-none-any.whl (98 kB)
Using cached fsspec-2026.7.0-py3-none-any.whl (206 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached tqdm-4.70.0-py3-none-any.whl (80 kB)
Using cached typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Using cached uvicorn-0.52.3-py3-none-any.whl (79 kB)
Installing collected packages: pytz, pydub, brotli, typing-inspection, tqdm, tomlkit, shellingham, semantic-version, pyyaml, python-multipart, pydantic-core, orjson, mdurl, markupsafe, hf-xet, h11, groovy, fsspec, filelock, click, audioop-lts, anyio, annotated-types, annotated-doc, uvicorn, starlette, pydantic, markdown-it-py, jinja2, httpcore, rich, httpx, fastapi, typer, safehttpx, huggingface-hub, gradio-client, hf-gradio, gradio

   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   --- ------------------------------------  3/39 [typing-inspection]
   ---- -----------------------------------  4/39 [tqdm]
   ----- ----------------------------------  5/39 [tomlkit]
   ------- --------------------------------  7/39 [semantic-version]
   -------- -------------------------------  8/39 [pyyaml]
   -------- -------------------------------  8/39 [pyyaml]
   -------- -------------------------------  8/39 [pyyaml]
   --------- ------------------------------  9/39 [python-multipart]
   ------------ --------------------------- 12/39 [mdurl]
   --------------- ------------------------ 15/39 [h11]
   --------------- ------------------------ 15/39 [h11]
   ----------------- ---------------------- 17/39 [fsspec]
   ----------------- ---------------------- 17/39 [fsspec]
   ----------------- ---------------------- 17/39 [fsspec]
   ----------------- ---------------------- 17/39 [fsspec]
   ------------------ --------------------- 18/39 [filelock]
   ------------------- -------------------- 19/39 [click]
   ------------------- -------------------- 19/39 [click]
   --------------------- ------------------ 21/39 [anyio]
   --------------------- ------------------ 21/39 [anyio]
   --------------------- ------------------ 21/39 [anyio]
   ------------------------ --------------- 24/39 [uvicorn]
   ------------------------ --------------- 24/39 [uvicorn]
   ------------------------- -------------- 25/39 [starlette]
   ------------------------- -------------- 25/39 [starlette]
   -------------------------- ------------- 26/39 [pydantic]
   -------------------------- ------------- 26/39 [pydantic]
   -------------------------- ------------- 26/39 [pydantic]
   -------------------------- ------------- 26/39 [pydantic]
   -------------------------- ------------- 26/39 [pydantic]
   --------------------------- ------------ 27/39 [markdown-it-py]
   --------------------------- ------------ 27/39 [markdown-it-py]
   --------------------------- ------------ 27/39 [markdown-it-py]
   ---------------------------- ----------- 28/39 [jinja2]
   ----------------------------- ---------- 29/39 [httpcore]
   ----------------------------- ---------- 29/39 [httpcore]
   ------------------------------ --------- 30/39 [rich]
   ------------------------------ --------- 30/39 [rich]
   ------------------------------ --------- 30/39 [rich]
   ------------------------------ --------- 30/39 [rich]
   ------------------------------- -------- 31/39 [httpx]
   ------------------------------- -------- 31/39 [httpx]
   -------------------------------- ------- 32/39 [fastapi]
   -------------------------------- ------- 32/39 [fastapi]
   --------------------------------- ------ 33/39 [typer]
   --------------------------------- ------ 33/39 [typer]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ------------------------------------ --- 36/39 [gradio-client]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   -------------------------------------- - 38/39 [gradio]
   ---------------------------------------- 39/39 [gradio]

Successfully installed annotated-doc-0.0.5 annotated-types-0.8.0 anyio-4.14.2 audioop-lts-0.2.2 brotli-1.2.0 click-8.4.2 fastapi-0.141.1 filelock-3.32.3 fsspec-2026.7.0 gradio-6.24.0 gradio-client-2.6.0 groovy-0.1.2 h11-0.16.0 hf-gradio-0.4.1 hf-xet-1.6.0 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.27.0 jinja2-3.1.6 markdown-it-py-4.2.0 markupsafe-3.0.3 mdurl-0.1.2 orjson-3.12.0 pydantic-2.13.4 pydantic-core-2.46.4 pydub-0.25.1 python-multipart-0.0.32 pytz-2026.3.post1 pyyaml-6.0.3 rich-15.0.0 safehttpx-0.1.7 semantic-version-2.10.0 shellingham-1.5.4 starlette-1.6.0 tomlkit-0.14.0 tqdm-4.70.0 typer-0.27.1 typing-inspection-0.4.4 uvicorn-0.52.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\Md Ziaul Haque\Zia_env\Scripts\python.exe -m pip install --upgrade pip

In [118]:
import gradio as gr
import pandas as pd

C:\Users\Md Ziaul Haque\Zia_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [119]:
# Create the prediction function

In [120]:
def predict_house_value(
    longitude,
    latitude,
    housing_median_age,
    total_rooms,
    total_bedrooms,
    population,
    households,
    median_income,
    ocean_proximity
):
    
    # Feature engineering
    rooms_per_household = total_rooms / households
    bedrooms_per_room = total_bedrooms / total_rooms
    population_per_household = population / households

    # Create raw input DataFrame
    new_house = pd.DataFrame({
        "longitude": [longitude],
        "latitude": [latitude],
        "housing_median_age": [housing_median_age],
        "total_rooms": [total_rooms],
        "total_bedrooms": [total_bedrooms],
        "population": [population],
        "households": [households],
        "median_income": [median_income],
        "rooms_per_household": [rooms_per_household],
        "bedrooms_per_room": [bedrooms_per_room],
        "population_per_household": [population_per_household],
        "ocean_proximity": [ocean_proximity]
    })

    # Prediction
    prediction = final_model.predict(new_house)[0]

    return f"${prediction:,.0f}"

# 🖥️ Step  — Build the interface

In [121]:
interface = gr.Interface(
    fn=predict_house_value,
    
    inputs=[
        gr.Number(label="Longitude"),
        gr.Number(label="Latitude"),
        gr.Number(label="Housing Median Age"),
        gr.Number(label="Total Rooms"),
        gr.Number(label="Total Bedrooms"),
        gr.Number(label="Population"),
        gr.Number(label="Households"),
        gr.Number(label="Median Income"),
        gr.Dropdown(
            choices=[
                "<1H OCEAN",
                "INLAND",
                "ISLAND",
                "NEAR BAY",
                "NEAR OCEAN"
            ],
            label="Ocean Proximity"
        )
    ],
    
    outputs=gr.Textbox(label="Predicted Median House Value"),
    
    title="🏠 California House Value Predictor",
    
    description="Enter house features and let our Random Forest model estimate the median house value."
)

# And finally launching the model interface

In [122]:
interface.launch()

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.

In [123]:
# Create the polished app skeleton

In [127]:
import gradio as gr

with gr.Blocks(title="California House Value Predictor") as app:

    gr.Markdown(
        """
        # 🏠 California House Value Predictor
        ### AI-powered median house-value estimation

        Enter the characteristics of a California housing district
        and let our trained **Random Forest** model estimate its
        median house value.
        """
    )

    with gr.Row():

        with gr.Column():
            gr.Markdown("### 📍 Location")

            longitude = gr.Number(
                label="Longitude",
                value=-118.25
            )

            latitude = gr.Number(
                label="Latitude",
                value=34.05
            )

        with gr.Column():
            gr.Markdown("### 🏡 Property")

            housing_median_age = gr.Number(
                label="Housing Median Age",
                value=25
            )

            total_rooms = gr.Number(
                label="Total Rooms",
                value=2500
            )

            total_bedrooms = gr.Number(
                label="Total Bedrooms",
                value=500
            )

    with gr.Row():

        with gr.Column():
            gr.Markdown("### 👨‍👩‍👧‍👦 Population & Households")

            population = gr.Number(
                label="Population",
                value=1200
            )

            households = gr.Number(
                label="Households",
                value=450
            )

        with gr.Column():
            gr.Markdown("### 💵 Income & Location Type")

            median_income = gr.Number(
                label="Median Income",
                value=6.5
            )

            ocean_proximity = gr.Dropdown(
                choices=[
                    "<1H OCEAN",
                    "INLAND",
                    "ISLAND",
                    "NEAR BAY",
                    "NEAR OCEAN"
                ],
                value="NEAR OCEAN",
                label="Ocean Proximity"
            )

    predict_button = gr.Button(
        "🔮 Predict House Value",
        variant="primary"
    )

    prediction_output = gr.Markdown(
        "### 💰 Prediction will appear here"
    )

    gr.Markdown(
        """
        ---
        **Model:** Random Forest Regression  
        **R²:** 0.8067  

        *The prediction is an ML estimate based on patterns learned
        from the California Housing dataset. It is not a guaranteed
        market valuation.*
        """
    )

    # 🔌 CONNECT BUTTON TO OUR ML MODEL
    predict_button.click(
        fn=predict_house_value,
        inputs=[
            longitude,
            latitude,
            housing_median_age,
            total_rooms,
            total_bedrooms,
            population,
            households,
            median_income,
            ocean_proximity
        ],
        outputs=prediction_output
    )


# 🚀 Launch the application
app.launch()

* Running on local URL:  http://127.0.0.1:7861
* To create a public link, set `share=True` in `launch()`.